export class FullAnimals {
  animal_id: number
  nickname_animals: string
  animal_species: string
  gender_animals: string
  photo_video: string
  responsible_person: string
  date_of_birth: string
  vaccination: string
  deworming: string
  sterilization_castration: string
  treatment: string
  content_item: string
  balance: string
  documents: string
  owner_animals: string
  name_content: string
  full_name_owner: string
  phone_content_items: string
  payment: string
  full_name_responsible: string
  phone_responsible: string
  vkontakte_link: string
  full_name: string
  phone_owners: string
  adress: string
  date_handed_over_to_owner: string
  return_date_reason: string
}
